### ISSUE TITLE
Couldnt open file

### ISSUE THREAD

**Issue by fvlntn** [danielgatis/darknetpy#1]
I'm working on Cygwin64 on Windows81
I compiled darknet on it, pip install darknetpy
When I try to run example.py:

```
Detector = Detector('/tmp/x64/',
                    '/tmp/x64/cfg/coco.data',
                    '/tmp/x64/cfg/yolo.cfg',
                    '/tmp/x64/yolo.weights')
```

It tells me: Couldn't open file: data/coco.names

My coco.data is the following:

```
classes= 80
train  = data/coco/trainvalno5k.txt
valid  = data/coco_testdev
#valid = data/coco_val_5k.list
names = data/coco.names
backup = backup/
eval=coco
```

Can I specify myself the data/coco.names path?

**Comment by fvlntn** [comment]
Went on Linux and bye bye

**Comment by danielgatis** [comment]
I never tested on cygwin. I do not know how to help :(
I'm sorry for the late reply.
