### ISSUE TITLE
darknetpy does not use GPU (CUDA 8)

### ISSUE THREAD

**Issue by firu** [danielgatis/darknetpy#10]
Hello,

I want to use darknetpy with GPU support but it does not work as explained below.

System details:
- GeForce GTX 1080/PCIe/SSE2
- Ubuntu 16.04.4 LTS 
- gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- Cuda compilation tools, release 8.0, V8.0.61

At first I try to install the way you described in your README.md with:
> GPU=1 pip3 install --upgrade --force-reinstall --ignore-installed darknetpy

Which failed with:
> nvcc fatal   : Unsupported gpu architecture 'compute_20'

So I downloaded the source code and updated setup.py by adding:
> sed('-gencode arch=compute_20,code=\[sm_20,sm_21\]', '', makefile)

I then arrived at the following error:
> nvcc fatal   : Path to libdevice library not specified

Which I fixed by adding:
> sed('nvcc', '/usr/local/cuda/bin/nvcc', makefile)

Now darknetpy compiles just fine, but when I want to use it in my Python application:

> ImportError: /home/hsrw/darknetpy/darknetpy-2.1/darknetpy/detector.cpython-35m-x86_64-linux-gnu.so: undefined symbol: __cudaUnregisterFatBinary

Could you provide any help?
Is there some flag I need to set, do I need to compile it with another Cuda version?

Thanks in advance!

**Comment by danielgatis** [comment]
sorry, I don't know.
