### ISSUE TITLE
Problem when installing

### ISSUE THREAD

**Issue by parayamelo** [danielgatis/darknetpy#12]
Hello, I am trying to install darknetpy

pip install darknetpy

getting the following error:

    warning: build failed, waiting for other jobs to finish...
    error: build failed
    error: cargo failed with code: 101
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x5Y4JO/darknetpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-NlQBqm-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-x5Y4JO/darknetpy/

I have installed rust, cargo, updated cargo, same issue. Do you know how to fix this?

I'm using Kubuntu 18.04

Thanking in advance, kind regards

**Comment by danielgatis** [comment]
try it before:
```
curl https://sh.rustup.rs -sSf | sh
rustup default nightly
```

or you can try install a pre-built binary:
```
pip3 install https://github.com/danielgatis/darknetpy/raw/master/dist/darknetpy-4.0-cp36-cp36m-linux_x86_64.whl --user
```
