### ISSUE TITLE
Could not build wheels for darknetpy which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by vishruthys** [danielgatis/darknetpy#13]
Running `rustc --crate-name log /home/vishruthys/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.6/src/lib.rs --color never --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="std"' -C metadata=09d91ec5988f7622 -C extra-filename=-09d91ec5988f7622 --out-dir /tmp/pip-install-jao6r_tk/darknetpy/target/release/deps -L dependency=/tmp/pip-install-jao6r_tk/darknetpy/target/release/deps --extern cfg_if=/tmp/pip-install-jao6r_tk/darknetpy/target/release/deps/libcfg_if-c9d276244f2d7157.rlib --cap-lints allow`
  error[E0554]: #![feature] may not be used on the stable release channel
   --> /home/vishruthys/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.10/src/lib.rs:6:35
    |
  6 | #![cfg_attr(feature = "const_fn", feature(const_fn))]
    |                                   ^^^^^^^^^^^^^^^^^^
  
  error: aborting due to previous error
  
  For more information about this error, try `rustc --explain E0554`.
  error: Could not compile `spin`.
  
  Caused by:
    process didn't exit successfully: `rustc --crate-name spin /home/vishruthys/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.10/src/lib.rs --color never --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="const_fn"' --cfg 'feature="default"' --cfg 'feature="once"' --cfg 'feature="unstable"' -C metadata=93d494a3902386b1 -C extra-filename=-93d494a3902386b1 --out-dir /tmp/pip-install-jao6r_tk/darknetpy/target/release/deps -L dependency=/tmp/pip-install-jao6r_tk/darknetpy/target/release/deps --cap-lints allow` (exit code: 1)
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  cargo rustc --lib --manifest-path Cargo.toml --features pyo3/extension-module pyo3/python3 --release --verbose -- --crate-type cdylib
  error: cargo failed with code: 101
  
  
  ----------------------------------------
  Failed building wheel for darknetpy
  Running setup.py clean for darknetpy
Failed to build darknetpy
Could not build wheels for darknetpy which use PEP 517 and cannot be installed directly

I want to build darknetpy with gpu and cudnn. How do i solve this? 
python=3.6.7
pip=19.0.1

**Comment by vishruthys** [comment]
Running `rustc --crate-name pyo3cls /home/vishruthys/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3cls-0.5.2/src/lib.rs --color never --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C opt-level=3 -C metadata=bd44bdc4d8de749b -C extra-filename=-bd44bdc4d8de749b --out-dir /tmp/pip-install-6r8b8bbh/darknetpy/target/release/deps -L dependency=/tmp/pip-install-6r8b8bbh/darknetpy/target/release/deps --extern proc_macro2=/tmp/pip-install-6r8b8bbh/darknetpy/target/release/deps/libproc_macro2-4554d5f0a5b1b566.rlib --extern pyo3_derive_backend=/tmp/pip-install-6r8b8bbh/darknetpy/target/release/deps/libpyo3_derive_backend-01ecfe7272ddf0a4.rlib --extern quote=/tmp/pip-install-6r8b8bbh/darknetpy/target/release/deps/libquote-9da6429ab6d4824c.rlib --extern syn=/tmp/pip-install-6r8b8bbh/darknetpy/target/release/deps/libsyn-d6189aa903428ae9.rlib --cap-lints allow`
       Running `/tmp/pip-install-6r8b8bbh/darknetpy/target/release/build/darknetpy-403dc654414c71ba/build-script-build`
  error: failed to run custom build command for `darknetpy v0.0.0 (/tmp/pip-install-6r8b8bbh/darknetpy)`
  process didn't exit successfully: `/tmp/pip-install-6r8b8bbh/darknetpy/target/release/build/darknetpy-403dc654414c71ba/build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-search=native=/tmp/darknet-61c9d02ec461e30d55762ec7669d6a1d3c356fb2
  cargo:rustc-link-lib=static=darknet
  
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', libcore/result.rs:1009:5
  note: Run with `RUST_BACKTRACE=1` for a backtrace.
  
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  cargo rustc --lib --manifest-path Cargo.toml --features pyo3/python3 pyo3/extension-module --release --verbose -- --crate-type cdylib
  error: cargo failed with code: 101
  
  
  ----------------------------------------
  Failed building wheel for darknetpy
  Running setup.py clean for darknetpy
Failed to build darknetpy
Could not build wheels for {} which use PEP 517 and cannot be installed directly


after googling i solved the e0554 error by installing the correct nightly.
But still getting a build error.

**Comment by danielgatis** [comment]
try it before run pip

```
sudo apt-get install clang
rustup default nightly
```

**Comment by vishruthys** [comment]
A new error 


Running `rustc --crate-name pyo3 /home/vishruthys/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.5.2/src/lib.rs --color never --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="extension-module"' --cfg 'feature="python3"' -C metadata=b5d262c02069a504 -C extra-filename=-b5d262c02069a504 --out-dir /tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps -L dependency=/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps --extern libc=/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/liblibc-4beaced3394e3329.rlib --extern mashup=/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libmashup-d5c1b12db3e9fdb4.rlib --extern num_traits=/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libnum_traits-a726b43970540310.rlib --extern pyo3cls=/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libpyo3cls-d3b9c615067616ef.so --extern spin=/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libspin-519558b3479a98cd.rlib --cap-lints allow --cfg Py_3_5 --cfg Py_3_6 --cfg Py_3 --cfg 'py_sys_config="WITH_THREAD"'`
       Running `rustc --crate-name darknetpy src/lib.rs --color never --crate-type cdylib --emit=dep-info,link -C opt-level=3 --crate-type cdylib --cfg 'feature="pyo3"' -C metadata=319ec42e987da8db --out-dir /tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps -L dependency=/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps --extern pyo3=/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libpyo3-b5d262c02069a504.rlib -L native=/tmp/darknet-61c9d02ec461e30d55762ec7669d6a1d3c356fb2 -l static=darknet`
  error: linking with `cc` failed: exit code: 1
    |
    = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.0.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.1.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.10.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.11.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.12.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.13.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.14.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.15.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.2.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.3.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.4.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.5.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.6.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.7.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.8.rcgu.o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.darknetpy.4br87j5f-cgu.9.rcgu.o" "-o" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libdarknetpy.so" "-Wl,--version-script=/tmp/rustcoJTsV7/list" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/darknetpy.1dvnhbrm11xme13s.rcgu.o" "-Wl,--gc-sections" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps" "-L" "/tmp/darknet-61c9d02ec461e30d55762ec7669d6a1d3c356fb2" "-L" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-ldarknet" "-Wl,--no-whole-archive" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libpyo3-b5d262c02069a504.rlib" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libnum_traits-a726b43970540310.rlib" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libspin-519558b3479a98cd.rlib" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libmashup-d5c1b12db3e9fdb4.rlib" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libproc_macro_hack-922ab6899f1d643e.rlib" "/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/liblibc-4beaced3394e3329.rlib" "-Wl,--start-group" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-45a786e8a0777836.rlib" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-f925729e2c5437d2.rlib" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-6319aefc056c3c06.rlib" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-5a27fe4e1c13f0fa.rlib" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-c4f220ce18cffe79.rlib" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-66a04f576027c5eb.rlib" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-e4051ec3106163a5.rlib" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-aea06f43e291f923.rlib" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-ea473ff4b202aff9.rlib" "-Wl,--end-group" "/home/vishruthys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-068c8601d08c8685.rlib" "-Wl,-Bdynamic" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil" "-shared"
    **= note: /usr/bin/ld: cannot find -ldarknet
            collect2: error: ld returned 1 exit status**
  
  
  error: aborting due to previous error
  
  error: Could not compile `darknetpy`.
  
  Caused by:
    process didn't exit successfully: `rustc --crate-name darknetpy src/lib.rs --color never --crate-type cdylib --emit=dep-info,link -C opt-level=3 --crate-type cdylib --cfg 'feature="pyo3"' -C metadata=319ec42e987da8db --out-dir /tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps -L dependency=/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps --extern pyo3=/tmp/pip-install-ha2jcdz_/darknetpy/target/release/deps/libpyo3-b5d262c02069a504.rlib -L native=/tmp/darknet-61c9d02ec461e30d55762ec7669d6a1d3c356fb2 -l static=darknet` (exit code: 1)
  cargo rustc --lib --manifest-path Cargo.toml --features pyo3/python3 pyo3/extension-module --release --verbose -- --crate-type cdylib
  error: cargo failed with code: 101
  
  
  ----------------------------------------
  Failed building wheel for darknetpy
  Running setup.py clean for darknetpy
Failed to build darknetpy
Could not build wheels for {} which use PEP 517 and cannot be installed directly

**Comment by vishruthys** [comment]
Also I'm running this command to compile 
**GPU=1 CUDNN=1 OPENCV=1 pip install darknetpy**

when i run
**cargo build**
from the cloned folder
i get this error
Compiling darknetpy v0.0.0 (/home/vishruthys/others/darknetpy)
error: failed to run custom build command for `darknetpy v0.0.0 (/home/vishruthys/others/darknetpy)`
process didn't exit successfully: `/home/vishruthys/others/darknetpy/target/debug/build/darknetpy-228cbe68b06cda30/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed


Or it would be great if you can share a prebuilt-binary with GPU=1 CUDNN=1 and OPENCV=1

**Comment by vishruthys** [comment]
when i run
**cargo build** 
from the cloned folder
i get this error
 Compiling darknetpy v0.0.0 (/home/vishruthys/others/darknetpy)
error: failed to run custom build command for `darknetpy v0.0.0 (/home/vishruthys/others/darknetpy)`
process didn't exit successfully: `/home/vishruthys/others/darknetpy/target/debug/build/darknetpy-228cbe68b06cda30/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by danielgatis** [comment]
try install without any option, like:

```
pip install darknetpy
```

then add one option at a time

```
GPU=1 pip install darknetpy
```

... and so on

this approach help to figure out the root cause of the error

**Comment by vishruthys** [comment]
getting the same error when i run
**GPU=1 pip install darknetpy**

should i run it from any particular directory?
and thanks for all the help!!

**Comment by themitigater** [comment]
Same issue here when trying pip install darknetpy on my mac. Any fixes for this?

**Comment by unrealwill** [comment]
Encountered the error too. 
Make sure you can run nvcc from the command line inside your PATH (ie export PATH=$PATH:/usr/local/cuda/bin)

It compiles without error but then I encounter : an undefined symbol when I do : 

`from darknetpy.detector import Detector`

`python3.5/site-packages/darknetpy/darknetpy.cpython-35m-x86_64-linux-gnu.so: undefined symbol: cudaPeekAtLastError`
(I have cuda10.0 )

I have tried a few tricks, but couldn't get it to work : 
(For example clone the repository and edited setup.py to point to master
```
        darknet_url = 'https://github.com/pjreddie/darknet/archive/master.zip'
        darknet_zip_file = os.path.join(tempdir, 'darknet.zip')
        darknet_root = os.path.join(tempdir, 'darknet-master')
```
)

Without GPU=1 I can get it to work fine.

Maybe you'll have more luck.

Currently I use the original darknet with the provided python file calling .encode() on the strings (in python3) and it works well.

**Comment by TheUsmanMirza** [comment]
This worked for me, Ubantu 16.04

$python3 -m pip install --no-use-pep517 darknetpy

**Comment by TheUsmanMirza** [comment]
Hi, @unrealwill

I am facing the same issue;

from darknetpy.detector import Detector    //NO MUDULE NAME darknetpy.darknetpy

but i have already installed it.
Did you find any solution? kindly let me know 

Thanks

Ubantu 16.04
python 3.6

**Comment by unrealwill** [comment]
@TheUsmanMirza Didn't spend a lot of time then trying to get the wrapper library darknetpy to work. Instead, as I said I used the python file of the original library https://github.com/pjreddie/darknet/blob/master/python/darknet.py copied it in my working repository

```
from darknet import load_net,load_meta,detectClass
net = load_net("yolov3.cfg".encode(), "yolov3.weights".encode(), 0)
meta = load_meta("coco.data".encode())
r = detectClass(net, meta, path.encode())
```
and it was working well enough for my purpose.

**Comment by avc94** [comment]
(venv) D:\Projects\Natuition\Sources\yolo_test>pip install darknetpy
Collecting darknetpy
  Using cached https://files.pythonhosted.org/packages/12/81/5f2618da622bda0bd72d45bf11eb9ed542109e59910ef573ddb2c65419d0/darknetpy-4.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: darknetpy
  Building wheel for darknetpy (PEP 517) ... error
  Complete output from command D:\Projects\Natuition\Sources\yolo_test\venv\Scripts\python.exe D:\Projects\Natuition\Sources\yolo_test\venv\lib\site-packages\pip-19.0.3-py3.7.egg\pip\_vendor\pep517\_in_process.py build_wheel C:\Users\Admin\AppData\Local\Temp\tmp0av4on
yd:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\darknetpy
  copying darknetpy\__init__.py -> build\lib\darknetpy
  running egg_info
  writing darknetpy.egg-info\PKG-INFO
  writing dependency_links to darknetpy.egg-info\dependency_links.txt
  writing top-level names to darknetpy.egg-info\top_level.txt
  reading manifest file 'darknetpy.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '__pycache__' found anywhere in distribution
  warning: no previously-included files matching '*.py[co]' found anywhere in distribution
  writing manifest file 'darknetpy.egg-info\SOURCES.txt'
  copying darknetpy\darknetpy.cpython-37m-darwin.so -> build\lib\darknetpy
  creating build\lib\darknetpy\detector
  copying darknetpy\detector\__init__.py -> build\lib\darknetpy\detector
  running build_ext
  "make" ­Ґ пў«пҐвбп ў­гваҐ­­Ґ© Ё«Ё ў­Ґи­Ґ©
  Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.
  running build_rust
  error: Can not find Rust compiler

  ----------------------------------------
  Failed building wheel for darknetpy
  Running setup.py clean for darknetpy
Failed to build darknetpy
Could not build wheels for darknetpy which use PEP 517 and cannot be installed directly



"pip install --no-use-pep517 darknetpy" also isn't working with the same error text (Rust compiler)
Win 10 Pro x64, Python 3.7.6

**Comment by claypackard** [comment]
> try it before run pip
> 
> ```
> sudo apt-get install clang
> rustup default nightly
> ```


try this specific nightly if you're having trouble and getting the error below - it worked for me. 

`rustup default nightly-2019-09-25`

The rust compiler available now enforces type_objects in a parent to be marked default in order to specialize them in impls (hope i said that right). this earlier version does not enforce that. Otherwise, you'll get this error (many times): 
`error[E0520]: `type_object` specializes an item from a parent `impl`, but that item is not marked `default``

in the future, someone may mark the parent type_objects default and this won't be necessary, but that's a little tangential to getting darknetpy to build tonight

**Comment by claypackard** [comment]
> (venv) D:\Projects\Natuition\Sources\yolo_test>pip install darknetpy
> Collecting darknetpy
> Using cached https://files.pythonhosted.org/packages/12/81/5f2618da622bda0bd72d45bf11eb9ed542109e59910ef573ddb2c65419d0/darknetpy-4.0.tar.gz
> Installing build dependencies ... done
> Getting requirements to build wheel ... done
> Preparing wheel metadata ... done
> Building wheels for collected packages: darknetpy
> Building wheel for darknetpy (PEP 517) ... error
> Complete output from command D:\Projects\Natuition\Sources\yolo_test\venv\Scripts\python.exe D:\Projects\Natuition\Sources\yolo_test\venv\lib\site-packages\pip-19.0.3-py3.7.egg\pip_vendor\pep517_in_process.py build_wheel C:\Users\Admin\AppData\Local\Temp\tmp0av4on
> yd:
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build\lib
> creating build\lib\darknetpy
> copying darknetpy__init__.py -> build\lib\darknetpy
> running egg_info
> writing darknetpy.egg-info\PKG-INFO
> writing dependency_links to darknetpy.egg-info\dependency_links.txt
> writing top-level names to darknetpy.egg-info\top_level.txt
> reading manifest file 'darknetpy.egg-info\SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no previously-included files matching '**pycache**' found anywhere in distribution
> warning: no previously-included files matching '*.py[co]' found anywhere in distribution
> writing manifest file 'darknetpy.egg-info\SOURCES.txt'
> copying darknetpy\darknetpy.cpython-37m-darwin.so -> build\lib\darknetpy
> creating build\lib\darknetpy\detector
> copying darknetpy\detector__init__.py -> build\lib\darknetpy\detector
> running build_ext
> "make" ­Ґ пў«пҐвбп ў­гваҐ­­Ґ© Ё«Ё ў­Ґи­Ґ©
> Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.
> running build_rust
**> error: Can not find Rust compiler**
> 
> Failed building wheel for darknetpy
> Running setup.py clean for darknetpy
> Failed to build darknetpy
> Could not build wheels for darknetpy which use PEP 517 and cannot be installed directly
> 
> "pip install --no-use-pep517 darknetpy" also isn't working with the same error text (Rust compiler)
> Win 10 Pro x64, Python 3.7.6

It appears you need to install the rust compiler. 
Install rust from the shell:
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
(referenced from: [https://www.rust-lang.org/tools/install](https://www.rust-lang.org/tools/install))
and then make sure the shell command `rustup` prints the rust usage stuff
see my other comment about needing a nightly from prior to version 1.39 (that'll be your next error :)

**Comment by nugrahari** [comment]
dont forget to activate: source $HOME/.cargo/env
and then run on terminal : rustup default nightly

its solved
