### ISSUE TITLE
is there the possibility to use darknetpy with videos like "./darknet detector demo" ? 

### ISSUE THREAD

**Issue by samux87** [danielgatis/darknetpy#14]
Hi,
I've tried to use your repo with opencv a video detection but at the moment I can't use detector.detect('path') directly with the frame. 

I've tried to save a frame to the hard drive and load from detector.detect but it is super slow (of course) and the Jupiter notebook doesn't work properly.

Could I ask you help for better understand what detector.detect does and try to implement a video detection as well?

**Comment by danielgatis** [comment]
sure, https://github.com/danielgatis/darknetpy/blob/master/src/lib.rs is a port in rust of this https://github.com/pjreddie/darknet/blob/master/examples/detector.c

**Comment by samux87** [comment]
Thank you for the reply! In the end, I used pyyolo for time reasons. Thank you again.
