### ISSUE TITLE
Trying to install the package on windows

### ISSUE THREAD

**Issue by GioLomia** [danielgatis/darknetpy#15]
I am trying to pip install the package: pip install darknetpy
Get this error.

 ERROR: Complete output from command 'c:\users\lomiag\appdata\local\new folder\library\python.exe' 'c:\users\lomiag\appdata\local\new folder\library\lib\site-packages\pip\_vendor\pep517\_i
n_process.py' build_wheel 'c:\users\lomiag\appdata\local\temp\tmpas3dfl':
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\darknetpy
  copying darknetpy\__init__.py -> build\lib\darknetpy
  running egg_info
  writing darknetpy.egg-info\PKG-INFO
  writing top-level names to darknetpy.egg-info\top_level.txt
  writing dependency_links to darknetpy.egg-info\dependency_links.txt
  reading manifest file 'darknetpy.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '__pycache__' found anywhere in distribution
  warning: no previously-included files matching '*.py[co]' found anywhere in distribution
  writing manifest file 'darknetpy.egg-info\SOURCES.txt'
  copying darknetpy\darknetpy.cpython-37m-darwin.so -> build\lib\darknetpy
  creating build\lib\darknetpy\detector
  copying darknetpy\detector\__init__.py -> build\lib\darknetpy\detector
  running build_ext
  'make' is not recognized as an internal or external command,
  operable program or batch file.
  running build_rust
  error: Can not find Rust compiler
  ----------------------------------------
  ERROR: Failed building wheel for darknetpy
  Running setup.py clean for darknetpy
Failed to build darknetpy
ERROR: Could not build wheels for darknetpy which use PEP 517 and cannot be installed directly

C:\Users\lomiag\PycharmProjects\GUI_Snow_leopard>sudo apt-get install clang
'sudo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\lomiag\PycharmProjects\GUI_Snow_leopard>pip install darknetpy
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop
support for Python 2.7.
Collecting darknetpy
  Using cached https://files.pythonhosted.org/packages/12/81/5f2618da622bda0bd72d45bf11eb9ed542109e59910ef573ddb2c65419d0/darknetpy-4.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: darknetpy
  Building wheel for darknetpy (PEP 517) ... error
  ERROR: Complete output from command 'c:\users\lomiag\appdata\local\new folder\library\python.exe' 'c:\users\lomiag\appdata\local\new folder\library\lib\site-packages\pip\_vendor\pep517\_i
n_process.py' build_wheel 'c:\users\lomiag\appdata\local\temp\tmpliaqj0':
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\darknetpy
  copying darknetpy\__init__.py -> build\lib\darknetpy
  running egg_info
  writing darknetpy.egg-info\PKG-INFO
  writing top-level names to darknetpy.egg-info\top_level.txt
  writing dependency_links to darknetpy.egg-info\dependency_links.txt
  reading manifest file 'darknetpy.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '__pycache__' found anywhere in distribution
  warning: no previously-included files matching '*.py[co]' found anywhere in distribution
  writing manifest file 'darknetpy.egg-info\SOURCES.txt'
  copying darknetpy\darknetpy.cpython-37m-darwin.so -> build\lib\darknetpy
  creating build\lib\darknetpy\detector
  copying darknetpy\detector\__init__.py -> build\lib\darknetpy\detector
  running build_ext
  'make' is not recognized as an internal or external command,
  operable program or batch file.
  running build_rust
  error: Can not find Rust compiler
  ----------------------------------------
  ERROR: Failed building wheel for darknetpy
  Running setup.py clean for darknetpy
Failed to build darknetpy
ERROR: Could not build wheels for darknetpy which use PEP 517 and cannot be installed directly

**Comment by danielgatis** [comment]
sorry. this package only works on Linux
