### ISSUE TITLE
Wrapping custom version of Darknet

### ISSUE THREAD

**Issue by scaramouche88** [danielgatis/darknetpy#19]
Hi,
First of all, nice repo.
I just wonder if it might be useful in my case: I have made some modifications to the original Darknet Yolov3-4 repo ([here](https://github.com/AlexeyAB/darknet))

Is there a way to call a specific darknet executable/specific libdarknet.so?
One of my objective is to compare my version of darknet with the original one, but I am also interested in wrapping darknet with a bunch of pre-/post-processing scripts in python...

**Comment by danielgatis** [comment]
sure, take a look at:
https://github.com/danielgatis/darknetpy/blob/master/setup.py#L31
