### ISSUE TITLE
Performance comparision with darknet C implementation

### ISSUE THREAD

**Issue by komalpharate** [danielgatis/darknetpy#2]
Hi,
Not an issue but a query.
I would like to know if there is any performance difference between C implementation and Python implementation. Like the time required to process images differs or it's the same?
Thanks

**Comment by danielgatis** [comment]
This library is just a wrapper, so performance issues are the same.

**Comment by komalpharate** [comment]
Okay. Nice to know that.
Thanks for your reply.

**Comment by komalpharate** [comment]
Can I know, what did you mean by theoretically?

**Comment by danielgatis** [comment]
Look here:
https://github.com/danielgatis/darknetpy/blob/master/extension/detector.c

and here:
https://github.com/pjreddie/darknet/blob/master/examples/detector.c

The main difference between them is just the use of python headers and the output in json.
