### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by qiumei1101** [danielgatis/darknetpy#20]
ERROR: Failed building wheel for darknetpy
Failed to build darknetpy
ERROR: Could not build wheels for darknetpy which use PEP 517 and cannot be installed directly

**Comment by iand111** [comment]
I ran into a similar issue, did you restart your system before running "rustup default nightly"?

**Comment by frank-qcd-qk** [comment]
I have the same issue, not sure why

**Comment by Ubranek** [comment]
had the same problem
help is to do from readme installating rust:
`curl https://sh.rustup.rs -sSf | sh `
and manually add to PATH
`export PATH="$HOME/.cargo/bin:$PATH"
`
then i had issue with:
"the package `darknetpy` depends on `pyo3`, with features: `python2` but `pyo3` does not have these features."

So i've reintalled wheel to version  founded in build-wheels.sh
`pip install wheel==0.31.1 auditwheel==2.0.0`

and finally i've ran into LLVM issue as there was no clang in system
`sudo apt install clang 
`
and only after that 
`pip install darknet` ran ok.

maybe that will help someone
