### ISSUE TITLE
Error while importing detector

### ISSUE THREAD

**Issue by mon28** [danielgatis/darknetpy#22]
How to check which yolo version is being used? How to change it?

Right now I get this error when importing Detector:

from darknetpy import detector
  File "/data/mtare/darknet-py/venv/lib/python3.6/site-packages/darknetpy/__init__.py", line 1, in <module>
    from .darknetpy import *
ImportError: /data/mtare/darknet-py/venv/lib/python3.6/site-packages/darknetpy/darknetpy.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSs4_Rep20_S_empty_rep_storageE

**Comment by josebenitezg** [comment]
I got this same error

**Comment by danielgatis** [comment]
> How to check which yolo version is being used? How to change it?

https://github.com/danielgatis/darknetpy/blob/master/setup.py#L31

sorry for late reply
