### ISSUE TITLE
YOLOV4 support?

### ISSUE THREAD

**Issue by 2MinuteWarning** [danielgatis/darknetpy#24]
I just installed your package and got the example.py to run on yolov3.weights but it doesn't work for yolov4.weights - dog.jpg doesn't show any detections.

Is something special required to enable Yolov4 support?

**Comment by danielgatis** [comment]
The lib gets the master version (v4) take a look at here:
https://github.com/danielgatis/darknetpy/blob/master/setup.py#L31

**Comment by GiorgioSgl** [comment]
I have the same problem here, seems there is no detection for a custom yolo detector.
I think the problem it's with yolov4-tiny actually, because yolov4 seem to work from some issues.
