### ISSUE TITLE
Ok on linux but can't install darknetpy on Windows 10

### ISSUE THREAD

**Issue by minertom** [danielgatis/darknetpy#25]
I am a linux person but can darknetpy be loaded on windows 10?

I am almost finished with an almost 2 year project using darknet and the original alexyab code. I have successfully used yolov3 and darknet for an object detection project on linux. I started with the original darknet_video.py code almost 2 years ago. It has changed substantially since then but I am using the original code.

Unfortunately I need to port this to windows 10. I have successfully ported the command line darknet functions to windows 10 using ./darknet.exe as opposed to the linux command line ./darknet... My inference works well.

My issue is that the python code on windows is run I get an attribute error and I believe that is because the dark.dll  is not invoked correctly in the python in the windows version.

netmain = darknet.load_net_custom(configpath.encode(attributeError: module 'darknet' has no attribute 'load_net_custom'

The original darknet_video.py code, posted almost 2 years ago at AlexeyAB, gives me the same error.

I have done research and some have suggested that that I install darknetpy but "pip -m install darknetpy" fails on windows. I have also attempted to load "rustup" but that also fails.

Can I load darknetpy on windows?

Thank You
Tom

**Comment by pkkota-dev** [comment]
yes am also facing issue when trying to install darknaetpy on windows 10. Is there any resolution ?

**Comment by danielgatis** [comment]
This lib is only compatible with linux at this moment.
