### ISSUE TITLE
Fail to run on google colab

### ISSUE THREAD

**Issue by itssanat** [danielgatis/darknetpy#29]
When I am running the cell to create a detector, my session is getting crashed.
This line of code is not working--
`detector = Detector('<absolute-path-to>/darknet/cfg/coco.data',
                    '<absolute-path-to>/darknet/cfg/yolo.cfg',
                    '<absolute-path-to>/darknet/yolo.weights')`

Is there any way to do it on Google Colab???

**Comment by migueBC** [comment]
not sure if relevant, but are you mounting your drive and the "absolute-path-to" leads to the actual path where those files are located?

**Comment by itssanat** [comment]
@migueBC I have done that. Now another problem is there.
```
results = detector.detect('<absolute-path-to>/darknet/data/dog.jpg')
print(results)
```
The above code is not working. Noting is printed. It's not even throwing any error. I think the problem is in the detect function.

**Comment by itssanat** [comment]
I am using Yolov4-tiny cfg file.

**Comment by smj007** [comment]
it seems to be working only on yolov3, did you try using those configs and weights?

**Comment by itssanat** [comment]
@smj007 No, I was using Yolov4.

**Comment by smj007** [comment]
@itssanat did you get it to work? It returns empty detections on yolov4 variants, works only on v3. Need to look into it and figure out what's causing the issue

**Comment by itssanat** [comment]
@smj007 No, it didn't work in my case.

**Comment by smj007** [comment]
@itssanat if you need yolov4 to work, using Opencv dnn works very well, or just use darknet_images.py from the Alexey darknet repo once you compile darknet
