### ISSUE TITLE
Error when installing: No module named request

### ISSUE THREAD

**Issue by xu932** [danielgatis/darknetpy#3]
When I install it in the virtual environment, it says no module named request, which is what I have installed. Error code are shown at the bottom.

// ============================ install request ==============================
(test) cam2@Precision-tower-7910:~$ pip install request
Requirement already satisfied: request in ./alex/python/test/lib/python2.7/site-packages
Requirement already satisfied: get in ./alex/python/test/lib/python2.7/site-packages (from request)
Requirement already satisfied: post in ./alex/python/test/lib/python2.7/site-packages (from request)
Requirement already satisfied: query-string in ./alex/python/test/lib/python2.7/site-packages (from get->request)
Requirement already satisfied: public in ./alex/python/test/lib/python2.7/site-packages (from query-string->get->request)

// ============================ install requests ==============================
(test) cam2@Precision-tower-7910:~$ pip install requests
Requirement already satisfied: requests in ./alex/python/test/lib/python2.7/site-packages
Requirement already satisfied: certifi>=2017.4.17 in ./alex/python/test/lib/python2.7/site-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./alex/python/test/lib/python2.7/site-packages (from requests)
Requirement already satisfied: idna<2.7,>=2.5 in ./alex/python/test/lib/python2.7/site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./alex/python/test/lib/python2.7/site-packages (from requests)

// ============================ install darknetpy ==============================
(test) cam2@Precision-tower-7910:~$ pip install darknetpy
Collecting darknetpy
  Using cached darknetpy-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1ZBH_A/darknetpy/setup.py", line 6, in <module>
        import urllib.request
    ImportError: No module named request
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1ZBH_A/darknetpy/

**Comment by danielgatis** [comment]
I submitted a new version to fix this issue. Let me know if its works. thanks.

**Comment by xu932** [comment]
I tried the updated version and I got following error message:

darknetpy requires Python '>=3' but the running Python is 2.7.12

I tried to add alias python='python3' but that does not solve the problem.

**Comment by danielgatis** [comment]
this extension only works with python 3 :( at this moment.

**Comment by xu932** [comment]
I do have python 3 installed. There are the errors exactly:

(test) cam2@Precision-tower-7910:~/alex$ pip install darknetpy
Collecting darknetpy
  Using cached darknetpy-2.1.tar.gz
darknetpy requires Python '>=3' but the running Python is 2.7.12

cam2@Precision-tower-7910:~$ python --version
Python 2.7.12
cam2@Precision-tower-7910:~$ python3 --version
Python 3.5.2

I actually have both installed and the command to choose python 3.5.2 is use python3 instead of python.

How can I set it so that it runs python3 when running pip install? Alias didn't work for me.

**Comment by danielgatis** [comment]
Try run pip3 install...

**Comment by xu932** [comment]
Solved it, thanks.
