### ISSUE TITLE
custom yolov4?

### ISSUE THREAD

**Issue by migueBC** [danielgatis/darknetpy#30]
hi there,

does it work using a custom yolov4 model? (developed using Colab)

using:
wmware workstation pro 16
ubuntu 18
python 3.7.9

virtualbox
centos 8
python 3.6/3.7

I tried to install it for a while... with lots of problems but I tried this...
OpenCV version: 4.5.1 (installed from source)
sudo snap install rustup --classic
sudo apt-get install clang
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
rustup default nightly
OPENCV=1 pip install darknetpy

and went through, it installed with no problems

running the detector directly on Darknet works fine, no errors whatsoever

but when attempting to run this darknetpy, I get... "Couldn't find activation function mish, going with ReLU" and prints nothing.
am I missing something?

**Comment by GiorgioSgl** [comment]
Seems it doesn't support YOLOv4 actually

**Comment by spullara** [comment]
Ah, this must be what I am running into. I'm using yolov4 with darknet and when I try the same parameters with darknetpy it comes up with an empty result.

**Comment by GiorgioSgl** [comment]
I solve using the module of opencvdnn, he work very well I really suggest it

**Comment by spullara** [comment]
I ended up using python-darknet-yolo-v4 which also works well. Thanks for the recommendation.
