### ISSUE TITLE
ImportError: /home/navras/.local/share/virtualenvs/yolo-tJKMRPlW/lib/python3.5/site-packages/darknetpy/detector.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2vv___pow_finite

### ISSUE THREAD

**Issue by bnawras** [danielgatis/darknetpy#5]
\>>> from darknetpy.detector import Detector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/navras/.local/share/virtualenvs/yolo-tJKMRPlW/lib/python3.5/site-packages/darknetpy/detector.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2vv___pow_finite
 (Debian, python3.5)

**Comment by bnawras** [comment]
fixed so:
import darknet
from darknetpy.detector import Detector

other problem:

82 Type not recognized: [yolo]
Unused field: 'mask = 6,7,8'
Unused field: 'anchors = 10,13,16,30,33,23,30,61,62,45,59,119,116,90,156,198,373,326'
Unused field: 'classes = 80'
Unused field: 'num = 9'
Unused field: 'jitter = .3'
Unused field: 'ignore_thresh = .7'
Unused field: 'truth_thresh = 1'
Unused field: 'random = 1'
   83 route  79
   84 conv    256  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 256
   85 Type not recognized: [upsample]
Unused field: 'stride = 2'
   86 route  85 61
   87 Layer before convolutional layer must output image.: Resource temporarily unavailable
python3: ./src/utils.c:224: error: Assertion `0' failed.

**Comment by LegalPrimes** [comment]
Hi bnavras,
I am also experiencing the same error. From some quick research it appears to be because darknetpy is not yet compatible with yolov3. Did you have any luck debugging or solving the issue?

**Comment by danielgatis** [comment]
darknetpy is only compatible with yolov2, specifically [this hash commit](https://github.com/danielgatis/darknetpy/blob/master/setup.py#L55), sorry :(

But I would be very happy if someone open a PR to make it compatible with yolo3 ;)
