### ISSUE TITLE
fail run  Detector 

### ISSUE THREAD

**Issue by jjoss** [danielgatis/darknetpy#8]
hi ! i am try to run darknetpy and print the following error ;
ImportError: /home/juanjo/env3/lib/python3.6/site-packages/darknetpy/detector.cpython-36m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
 help?

**Comment by yuvarajvemula** [comment]
me to getting similar error.. 

```
Traceback (most recent call last):
  File "yo.py", line 1, in <module>
    from darknetpy.detector import Detector
ImportError: /home/shivaraj/.local/share/virtualenvs/test-python-FsukhohF/lib/python3.6/site-packages/darknetpy/detector.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2vv___pow_finite

```

I think it's may be i am using yolo v3 .. 

If that's the reason for error what are the alternatives to use yolo v3 ?

**Comment by jjoss** [comment]
hi man! go darknet/examples/darknet.py see the path for files , example  r = load_image(b"/home/darknet/.....") add the .cfg and .weights.
e.g.
net = load_net(b"/home/darknet/cfg/yolov3.cfg",b"/home/juanjo/darknet/cfg/yolov3.weights", 0)
 im = load_image(b"/home/darknet/data/eagle.jpg", 0, 0)
 meta = load_meta(b"/home/darknet/cfg/coco.data")
and download yolov3.weights
the b, convert string to char and work for me!

**Comment by yuvarajvemula** [comment]
Hi @jjoss 
But I am getting the error even after commenting the remaining except import statement.. 
So I think issue is not in this part of code  
```
net = load_net(b"/home/darknet/cfg/yolov3.cfg",b"/home/juanjo/darknet/cfg/yolov3.weights", 0)
im = load_image(b"/home/darknet/data/eagle.jpg", 0, 0)
meta = load_meta(b"/home/darknet/cfg/coco.data")
```
The following line itself causing program to exit..

```
    from darknetpy.detector import Detector
```
Issue is something else, I think.. However thanks for your kind reply.. :+1:

**Comment by danielgatis** [comment]
@shivarajnaidu for now its only works with yolov2. PRs to support v3 are welcome ;)

**Comment by TheUsmanMirza** [comment]
@shivarajnaidu 

i am facing the same issue, did you find any solution kindly let me know..
 "from darknetpy.detector import Detector"


thanks
